```{r}
# Task 2: Import Libraries
library(tidyverse)
#install.packages("readxl")
library(readxl)
#install.packages("h2o")
library(h2o)
```

```{r}
#task 3: Read the Excel Sheets
path <- "~/Desktop/UCI_bank_marketing.xlsx"
sheets <- excel_sheets(path)
```

```{r}
#task 3.1: Explore data in each sheet
sheets %>%
  map(~ read_excel(path=path, sheet = .)) %>%
  set_names(sheets)

```

```{r}
#task 3.2: Join data by Id column(VLOOKUP equivalent)
data_joined <- sheets[4:7] %>%
  map(~ read_excel(path =path, sheet = .)) %>%
  reduce(left_join)

table(data_joined$TERM_DEPOSIT)
```

```{r}
#task 4: start h2o cluster
h2o.init(max_mem_size = "4g")
```

```{r}
#task 4.1: Data preparation
data_joined <- data_joined %>%
  mutate_if(is.character, as.factor)

train <- as.h2o(data_joined)

y <- "TERM_DEPOSIT"
#IF VALUES AND TERMDEPOSITS WERE ENCODED IN 0 OR 1 USE
#train[,y] <- as.factor(train[.y])
x <- setdiff(names(train), c(y, "ID"))

```

```{r}
#task 5 :H2o AutoML training
aml <- h2o.automl(
  x = x,
  y = y,
  training_frame = train,
  max_runtime_secs = 600,
  balance_classes = TRUE
)

```

```{r}
#task 6: View Automl leaderboard
lb <- aml@leaderboard
print(lb, n=nrow(lb))

```

```{r}
#task 6.1 Ensemble Exploration
model_ids <- as.data.frame(aml@leaderboard$model_id)[,1]

se <- h2o.getModel(grep("StackedEnsemble_AllModels", model_ids, value = TRUE)[1])

metalearner <- h2o.getModel(se@model$metalearner$name)
h2o.varimp(metalearner)
h2o.varimp_plot(metalearner)
```

```{r}
#task 6.2: baselearner Variable Importance

gbm <- h2o.getModel(grep("GBM_grid", model_ids, value=TRUE)[1])
h2o.varimp(gbm)

h2o.varimp_plot(gbm)

```

